package com.shiftmate.ui.shift

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel
import com.shiftmate.domain.model.ShiftEntry
import com.shiftmate.domain.model.Staff
import com.shiftmate.domain.model.TimeBlock
import java.time.LocalDate
import java.time.YearMonth

private val blockColors = listOf(
    Color(0xFFDCEDC8) to Color(0xFF33691E),
    Color(0xFFFFCDD2) to Color(0xFFB71C1C),
    Color(0xFFE1BEE7) to Color(0xFF4A148C),
    Color(0xFFFFE0B2) to Color(0xFFE65100)
)

@Composable
fun ShiftScreen(vm: ShiftViewModel = hiltViewModel()) {
    val context = LocalContext.current
    val month by vm.currentMonth.collectAsState()
    val staff by vm.staff.collectAsState()
    val blocks by vm.blocks.collectAsState()
    val entries by vm.entries.collectAsState()
    val violations by vm.violations.collectAsState()
    val generated by vm.generated.collectAsState()
    val errorMessage by vm.errorMessage.collectAsState()

    // Edit cell dialog state
    var editTarget by remember { mutableStateOf<Pair<Staff, LocalDate>?>(null) }

    if (errorMessage != null) {
        AlertDialog(
            onDismissRequest = { vm.clearError() },
            title = { Text("シフト生成できません") },
            text = { Text(errorMessage!!) },
            confirmButton = { TextButton(onClick = { vm.clearError() }) { Text("OK") } }
        )
    }

    editTarget?.let { (targetStaff, date) ->
        EditCellDialog(
            staff = targetStaff,
            date = date,
            blocks = blocks,
            currentBlockId = entries.find { it.staffId == targetStaff.id && it.date == date }?.blockId,
            onSelect = { blockId -> vm.setEntry(targetStaff.id, date, blockId); editTarget = null },
            onDismiss = { editTarget = null }
        )
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("シフト表") },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.primary,
                    titleContentColor = Color.White
                )
            )
        }
    ) { padding ->
        LazyColumn(
            Modifier.padding(padding),
            contentPadding = PaddingValues(12.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            item {
                Card(modifier = Modifier.fillMaxWidth()) {
                    Column(Modifier.padding(16.dp)) {
                        Row(
                            Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.Center,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            IconButton(onClick = { vm.prevMonth() }) { Icon(Icons.Filled.ChevronLeft, contentDescription = "前月") }
                            Text(
                                "${month.year}年${month.monthValue}月",
                                fontSize = 18.sp, fontWeight = FontWeight.Bold,
                                modifier = Modifier.width(140.dp), textAlign = TextAlign.Center
                            )
                            IconButton(onClick = { vm.nextMonth() }) { Icon(Icons.Filled.ChevronRight, contentDescription = "翌月") }
                        }
                        Spacer(Modifier.height(8.dp))
                        Button(
                            onClick = { vm.generateShifts() },
                            modifier = Modifier.fillMaxWidth().height(52.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary)
                        ) {
                            Icon(Icons.Filled.Refresh, contentDescription = null)
                            Spacer(Modifier.width(8.dp))
                            Text("シフト自動生成", fontSize = 16.sp)
                        }
                    }
                }
            }

            if (!generated) {
                item {
                    Card(modifier = Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(containerColor = Color(0xFFF0F7E8))) {
                        Text(
                            "上のボタンを押してシフトを生成してください。\n生成後はセルをタップして手動で編集もできます。",
                            Modifier.padding(16.dp), fontSize = 13.sp, color = MaterialTheme.colorScheme.primary
                        )
                    }
                }
            }

            if (generated) {
                if (violations.isNotEmpty()) {
                    item {
                        Card(modifier = Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(containerColor = Color(0xFFFFF8E1))) {
                            Column(Modifier.padding(16.dp)) {
                                Text("⚠️ ${violations.size} 件の問題", fontWeight = FontWeight.Bold, color = Color(0xFFE65100))
                                Spacer(Modifier.height(8.dp))
                                violations.take(6).forEach { v -> Text("• $v", fontSize = 12.sp, color = Color(0xFFE65100)) }
                                if (violations.size > 6) Text("他 ${violations.size - 6} 件...", fontSize = 12.sp, color = Color.Gray)
                            }
                        }
                    }
                } else {
                    item {
                        Card(modifier = Modifier.fillMaxWidth(), colors = CardDefaults.cardColors(containerColor = Color(0xFFE8F5E9))) {
                            Text("✅ 全制約を満たしたシフトが生成されました！", Modifier.padding(16.dp), color = Color(0xFF2E7D32))
                        }
                    }
                }

                item {
                    Text(
                        "※ セルをタップして個別に編集できます",
                        fontSize = 11.sp, color = Color.Gray, modifier = Modifier.padding(horizontal = 4.dp)
                    )
                }

                item {
                    ShiftTable(
                        month = month, staff = staff, blocks = blocks, entries = entries,
                        onCellClick = { s, d -> editTarget = s to d }
                    )
                }

                item {
                    Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                        OutlinedButton(onClick = { vm.exportCsv(context) }, modifier = Modifier.weight(1f)) {
                            Icon(Icons.Filled.Download, contentDescription = null)
                            Spacer(Modifier.width(4.dp))
                            Text("CSV")
                        }
                        OutlinedButton(onClick = { vm.exportPdf(context) }, modifier = Modifier.weight(1f)) {
                            Icon(Icons.Filled.Description, contentDescription = null)
                            Spacer(Modifier.width(4.dp))
                            Text("PDF")
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun EditCellDialog(
    staff: Staff,
    date: LocalDate,
    blocks: List<TimeBlock>,
    currentBlockId: Long?,
    onSelect: (Long?) -> Unit,
    onDismiss: () -> Unit
) {
    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("${staff.name} — ${date.monthValue}/${date.dayOfMonth}") },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                Text("時間帯を選択してください", fontSize = 13.sp, color = Color.Gray)
                blocks.forEachIndexed { idx, block ->
                    val (bg, fg) = blockColors.getOrElse(idx) { blockColors[0] }
                    val selected = block.id == currentBlockId
                    Surface(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clip(RoundedCornerShape(8.dp))
                            .border(2.dp, if (selected) fg else Color.Transparent, RoundedCornerShape(8.dp))
                            .clickable { onSelect(block.id) },
                        color = if (selected) bg else Color(0xFFF5F5F5)
                    ) {
                        Row(Modifier.padding(12.dp), verticalAlignment = Alignment.CenterVertically) {
                            Text(block.name, fontWeight = FontWeight.SemiBold, color = if (selected) fg else Color.Black, modifier = Modifier.weight(1f))
                            Text("${block.start}〜${block.end}", fontSize = 12.sp, color = if (selected) fg else Color.Gray)
                        }
                    }
                }
            }
        },
        confirmButton = {},
        dismissButton = {
            Row {
                TextButton(onClick = { onSelect(null) }) { Text("クリア", color = Color(0xFFE53935)) }
                TextButton(onClick = onDismiss) { Text("キャンセル") }
            }
        }
    )
}

@Composable
private fun ShiftTable(
    month: YearMonth,
    staff: List<Staff>,
    blocks: List<TimeBlock>,
    entries: List<ShiftEntry>,
    onCellClick: (Staff, LocalDate) -> Unit
) {
    val blockMap = blocks.associateBy { it.id }
    val entryMap = entries.groupBy { it.staffId to it.date }
    val daysInMonth = month.lengthOfMonth()
    val dates = (1..daysInMonth).map { LocalDate.of(month.year, month.monthValue, it) }
    val scrollState = rememberScrollState()

    Card(modifier = Modifier.fillMaxWidth()) {
        Box(Modifier.horizontalScroll(scrollState)) {
            Column {
                // Header
                Row(Modifier.background(MaterialTheme.colorScheme.primary)) {
                    Text("スタッフ", Modifier.width(100.dp).padding(4.dp), color = Color.White, fontSize = 9.sp, fontWeight = FontWeight.Bold)
                    dates.forEach { d ->
                        val dow = d.dayOfWeek.value % 7
                        val bg = if (dow == 0) Color(0xFFB71C1C) else if (dow == 6) Color(0xFF558B2F) else MaterialTheme.colorScheme.primary
                        Column(
                            Modifier.width(36.dp).background(bg).padding(vertical = 4.dp),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Text(d.dayOfMonth.toString(), color = Color.White, fontSize = 9.sp, fontWeight = FontWeight.Bold)
                            Text(listOf("日","月","火","水","木","金","土")[dow], color = Color.White, fontSize = 7.sp)
                        }
                    }
                    Text("日数", Modifier.width(36.dp).padding(4.dp), color = Color.White, fontSize = 9.sp, textAlign = TextAlign.Center)
                    Text("時間", Modifier.width(40.dp).padding(4.dp), color = Color.White, fontSize = 9.sp, textAlign = TextAlign.Center)
                }

                staff.forEach { s ->
                    val myEntries = entries.filter { it.staffId == s.id }
                    val workDays = myEntries.map { it.date }.distinct().size
                    val workHours = myEntries.sumOf { blockMap[it.blockId]?.durationHours ?: 0.0 }

                    Row(Modifier.background(Color.White)) {
                        Text(s.name, Modifier.width(100.dp).padding(4.dp), fontSize = 9.sp, fontWeight = FontWeight.SemiBold)
                        dates.forEach { d ->
                            val dow = d.dayOfWeek.value % 7
                            val bg = if (dow == 0) Color(0xFFFFF9F9) else if (dow == 6) Color(0xFFF3FFF0) else Color.White
                            Box(
                                Modifier.width(36.dp).background(bg).clickable { onCellClick(s, d) },
                                contentAlignment = Alignment.Center
                            ) {
                                val dayEntries = entryMap[s.id to d]
                                if (!dayEntries.isNullOrEmpty()) {
                                    val blockIdx = blocks.indexOfFirst { it.id == dayEntries.first().blockId }
                                    val (chipBg, chipFg) = blockColors.getOrElse(blockIdx) { blockColors[0] }
                                    Surface(
                                        color = chipBg, shape = MaterialTheme.shapes.extraSmall,
                                        modifier = Modifier.padding(1.dp)
                                    ) {
                                        Text(
                                            blockMap[dayEntries.first().blockId]?.name?.take(2) ?: "?",
                                            Modifier.padding(horizontal = 2.dp, vertical = 1.dp),
                                            fontSize = 8.sp, color = chipFg, fontWeight = FontWeight.Bold
                                        )
                                    }
                                } else {
                                    Text("－", fontSize = 9.sp, color = Color.LightGray)
                                }
                            }
                        }
                        Text(workDays.toString(), Modifier.width(36.dp).padding(vertical = 4.dp), fontSize = 9.sp, fontWeight = FontWeight.Bold, textAlign = TextAlign.Center)
                        Text("${String.format("%.0f", workHours)}h", Modifier.width(40.dp).padding(vertical = 4.dp), fontSize = 9.sp, textAlign = TextAlign.Center)
                    }
                    HorizontalDivider(color = Color(0xFFEEEEEE))
                }

                // Understaffed row
                Row(Modifier.background(Color(0xFFFAFAFA))) {
                    Text("充足", Modifier.width(100.dp).padding(4.dp), fontSize = 9.sp, color = Color.Gray)
                    dates.forEach { d ->
                        val dayEntries = entries.filter { it.date == d }
                        val understaffed = blocks.any { block -> dayEntries.count { it.blockId == block.id } < block.required }
                        Box(Modifier.width(36.dp), contentAlignment = Alignment.Center) {
                            Text(if (understaffed) "!" else "✓", fontSize = 10.sp,
                                color = if (understaffed) Color(0xFFE53935) else MaterialTheme.colorScheme.primary,
                                fontWeight = FontWeight.Bold)
                        }
                    }
                }
            }
        }
    }
}
